name: botsort
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip=22.1.2
  - cudatoolkit=11.1
  - pytorch=1.9.1
  - pytorch-gpu=1.9.1
  - torchvision=0.10.1
  - pip:
      - numpy
      - opencv-python
      - loguru
      - scikit-image
      - scikit-learn
      - tqdm
      - torchvision>=0.10.0
      - Pillow
      - thop
      - ninja
      - tabulate
      - tensorboard
      - lap
      - motmetrics
      - filterpy
      - h5py
      - matplotlib
      - scipy
      - prettytable
      - easydict
      - tensorboard
      - pyyaml
      - yacs
      - termcolor
      - gdown
      - onnx
      - onnxruntime
      - onnx-simplifier
      - pycocotools@git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
      - cython
      - faiss-gpu
